In [2]:
pip install azureml-core

Requirement already satisfied: azureml-core in c:\users\gael1\anaconda3\lib\site-packages (1.61.0.post4)
Requirement already satisfied: pytz in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (2024.1)
Requirement already satisfied: backports.tempfile in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (1.0)
Requirement already satisfied: pathspec<1.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (0.10.3)
Requirement already satisfied: requests<3.0.0,>=2.19.1 in c:\users\gael1\anaconda3\lib\site-packages (from requests[socks]<3.0.0,>=2.19.1->azureml-core) (2.32.3)
Requirement already satisfied: msal<2.0.0,>=1.15.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (1.39.0)
Requirement already satisfied: msal-extensions<=2.0.0,>=0.3.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (1.3.1)
Requirement already satisfied: knack<0.13.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (0.12.0)
Requirement already satisfied: azure-core<2.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (1.41.0)
Requirement already satisfied: pkginfo in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (1.12.0)
Requirement already satisfied: argcomplete<4 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (3.7.2)
Requirement already satisfied: humanfriendly<11.0,>=4.7 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (10.0)
Requirement already satisfied: paramiko<4.0.0,>=2.0.8 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (3.5.1)
Requirement already satisfied: azure-mgmt-resource<=24.0.0,>=15.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (24.0.0)
Requirement already satisfied: azure-mgmt-containerregistry<15,>=8.2.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (14.0.0)
Requirement already satisfied: azure-mgmt-storage<=24.0.0,>=16.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (24.0.0)
Requirement already satisfied: azure-mgmt-keyvault<12.0.0,>=0.40.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (11.0.0)
Requirement already satisfied: azure-mgmt-authorization<5,>=0.40.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (4.0.0)
Requirement already satisfied: azure-mgmt-network<=30.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (30.0.0)
Requirement already satisfied: azure-graphrbac<1.0.0,>=0.40.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (0.61.2)
Requirement already satisfied: azure-common<2.0.0,>=1.1.12 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (1.1.28)
Requirement already satisfied: msrest<=0.7.1,>=0.5.1 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (0.7.1)
Requirement already satisfied: msrestazure<=0.7,>=0.4.33 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (0.6.4.post1)
Requirement already satisfied: urllib3<3.0.0,>1.26.17 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (2.3.0)
Requirement already satisfied: packaging<26.0,>=20.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (24.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.7.3 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (2.9.0.post0)
Requirement already satisfied: ndg-httpsclient<=0.5.1 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (0.5.1)
Requirement already satisfied: SecretStorage<4.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (3.5.0)
Requirement already satisfied: jsonpickle<5.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (4.1.2)
Requirement already satisfied: contextlib2<22.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (21.6.0)
Requirement already satisfied: docker<8.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (7.2.0)
Requirement already satisfied: PyJWT<3.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (2.10.1)
Requirement already satisfied: adal<=1.2.7,>=1.2.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (1.2.7)
Requirement already satisfied: pyopenssl<=26.0.0,>=25.3.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (26.0.0)
Requirement already satisfied: jmespath<2.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from azureml-core) (1.0.1)
Requirement already satisfied: cryptography>=1.1.0 in c:\users\gael1\anaconda3\lib\site-packages (from adal<=1.2.7,>=1.2.0->azureml-core) (46.0.7)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\gael1\anaconda3\lib\site-packages (from azure-core<2.0.0->azureml-core) (4.12.2)
Requirement already satisfied: isodate<1.0.0,>=0.6.1 in c:\users\gael1\anaconda3\lib\site-packages (from azure-mgmt-authorization<5,>=0.40.0->azureml-core) (0.7.2)
Requirement already satisfied: azure-mgmt-core<2.0.0,>=1.3.2 in c:\users\gael1\anaconda3\lib\site-packages (from azure-mgmt-authorization<5,>=0.40.0->azureml-core) (1.6.0)
Requirement already satisfied: pywin32>=304 in c:\users\gael1\anaconda3\lib\site-packages (from docker<8.0.0->azureml-core) (308)
Requirement already satisfied: pyreadline3 in c:\users\gael1\anaconda3\lib\site-packages (from humanfriendly<11.0,>=4.7->azureml-core) (3.5.6)
Requirement already satisfied: pygments in c:\users\gael1\anaconda3\lib\site-packages (from knack<0.13.0->azureml-core) (2.19.1)
Requirement already satisfied: pyyaml in c:\users\gael1\anaconda3\lib\site-packages (from knack<0.13.0->azureml-core) (6.0.2)
Requirement already satisfied: tabulate in c:\users\gael1\anaconda3\lib\site-packages (from knack<0.13.0->azureml-core) (0.9.0)
Requirement already satisfied: cffi>=2.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from cryptography>=1.1.0->adal<=1.2.7,>=1.2.0->azureml-core) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\gael1\anaconda3\lib\site-packages (from msrest<=0.7.1,>=0.5.1->azureml-core) (2025.11.12)
Requirement already satisfied: requests-oauthlib>=0.5.0 in c:\users\gael1\anaconda3\lib\site-packages (from msrest<=0.7.1,>=0.5.1->azureml-core) (2.0.0)
Requirement already satisfied: six in c:\users\gael1\anaconda3\lib\site-packages (from msrestazure<=0.7,>=0.4.33->azureml-core) (1.17.0)
Requirement already satisfied: pyasn1>=0.1.1 in c:\users\gael1\anaconda3\lib\site-packages (from ndg-httpsclient<=0.5.1->azureml-core) (0.4.8)
Requirement already satisfied: bcrypt>=3.2 in c:\users\gael1\anaconda3\lib\site-packages (from paramiko<4.0.0,>=2.0.8->azureml-core) (4.3.0)
Requirement already satisfied: pynacl>=1.5 in c:\users\gael1\anaconda3\lib\site-packages (from paramiko<4.0.0,>=2.0.8->azureml-core) (1.5.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\gael1\anaconda3\lib\site-packages (from requests<3.0.0,>=2.19.1->requests[socks]<3.0.0,>=2.19.1->azureml-core) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\gael1\anaconda3\lib\site-packages (from requests<3.0.0,>=2.19.1->requests[socks]<3.0.0,>=2.19.1->azureml-core) (3.7)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in c:\users\gael1\anaconda3\lib\site-packages (from requests[socks]<3.0.0,>=2.19.1->azureml-core) (1.7.1)
Requirement already satisfied: jeepney>=0.6 in c:\users\gael1\anaconda3\lib\site-packages (from SecretStorage<4.0.0->azureml-core) (0.9.0)
Requirement already satisfied: pycparser in c:\users\gael1\anaconda3\lib\site-packages (from cffi>=2.0.0->cryptography>=1.1.0->adal<=1.2.7,>=1.2.0->azureml-core) (2.21)
Requirement already satisfied: oauthlib>=3.0.0 in c:\users\gael1\anaconda3\lib\site-packages (from requests-oauthlib>=0.5.0->msrest<=0.7.1,>=0.5.1->azureml-core) (4.0.0)
Requirement already satisfied: backports.weakref in c:\users\gael1\anaconda3\lib\site-packages (from backports.tempfile->azureml-core) (1.0.post1)
Note: you may need to restart the kernel to use updated packages.

In [3]:
!pip install azureml-sdk

Collecting azureml-sdk
  Using cached azureml_sdk-1.62.0-py3-none-any.whl.metadata (3.8 kB)
Requirement already satisfied: azureml-core in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-sdk) (1.61.0.post4)
Collecting azureml-dataset-runtime~=1.62.0 (from azureml-dataset-runtime[fuse]~=1.62.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.62.0.post1-py3-none-any.whl.metadata (1.4 kB)
Collecting azureml-train-core~=1.62.0 (from azureml-sdk)
  Using cached azureml_train_core-1.62.0-py3-none-any.whl.metadata (2.0 kB)
INFO: pip is looking at multiple versions of azureml-sdk to determine which version is compatible with other requirements. This could take a while.
Collecting azureml-sdk
  Using cached azureml_sdk-1.61.0-py3-none-any.whl.metadata (3.8 kB)
Collecting azureml-dataset-runtime~=1.61.0 (from azureml-dataset-runtime[fuse]~=1.61.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.61.0-py3-none-any.whl.metadata (1.4 kB)
Collecting azureml-train-core~=1.61.0 (from azureml-sdk)
  Using cached azureml_train_core-1.61.0-py3-none-any.whl.metadata (2.0 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.60.0-py3-none-any.whl.metadata (3.8 kB)
Collecting azureml-core~=1.60.0 (from azureml-sdk)
  Using cached azureml_core-1.60.0.post1-py3-none-any.whl.metadata (3.4 kB)
Collecting azureml-dataset-runtime~=1.60.0 (from azureml-dataset-runtime[fuse]~=1.60.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.60.0-py3-none-any.whl.metadata (1.4 kB)
Collecting azureml-train-core~=1.60.0 (from azureml-sdk)
  Using cached azureml_train_core-1.60.0-py3-none-any.whl.metadata (2.0 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.59.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.59.0 (from azureml-sdk)
  Using cached azureml_core-1.59.0.post2-py3-none-any.whl.metadata (3.4 kB)
Collecting azureml-dataset-runtime~=1.59.0 (from azureml-dataset-runtime[fuse]~=1.59.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.59.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.59.0 (from azureml-sdk)
  Using cached azureml_train_core-1.59.0-py3-none-any.whl.metadata (1.8 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.58.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.58.0 (from azureml-sdk)
  Using cached azureml_core-1.58.0.post1-py3-none-any.whl.metadata (3.2 kB)
Collecting azureml-dataset-runtime~=1.58.0 (from azureml-dataset-runtime[fuse]~=1.58.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.58.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.58.0 (from azureml-sdk)
  Using cached azureml_train_core-1.58.0-py3-none-any.whl.metadata (1.8 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.57.0-py3-none-any.whl.metadata (3.5 kB)
Collecting azureml-core~=1.57.0 (from azureml-sdk)
  Using cached azureml_core-1.57.0.post3-py3-none-any.whl.metadata (3.1 kB)
Collecting azureml-dataset-runtime~=1.57.0 (from azureml-dataset-runtime[fuse]~=1.57.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.57.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.57.0 (from azureml-sdk)
  Using cached azureml_train_core-1.57.0-py3-none-any.whl.metadata (1.7 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.56.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.56.0 (from azureml-sdk)
  Using cached azureml_core-1.56.0-py3-none-any.whl.metadata (3.1 kB)
Collecting azureml-dataset-runtime~=1.56.0 (from azureml-dataset-runtime[fuse]~=1.56.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.56.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.56.0 (from azureml-sdk)
  Using cached azureml_train_core-1.56.0-py3-none-any.whl.metadata (1.7 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.55.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.55.0 (from azureml-sdk)
  Using cached azureml_core-1.55.0.post2-py3-none-any.whl.metadata (3.2 kB)
Collecting azureml-dataset-runtime~=1.55.0 (from azureml-dataset-runtime[fuse]~=1.55.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.55.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.55.0 (from azureml-sdk)
  Using cached azureml_train_core-1.55.0-py3-none-any.whl.metadata (1.7 kB)
INFO: pip is still looking at multiple versions of azureml-sdk to determine which version is compatible with other requirements. This could take a while.
Collecting azureml-sdk
  Using cached azureml_sdk-1.54.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.54.0 (from azureml-sdk)
  Using cached azureml_core-1.54.0.post1-py3-none-any.whl.metadata (3.2 kB)
Collecting azureml-dataset-runtime~=1.54.0 (from azureml-dataset-runtime[fuse]~=1.54.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.54.0.post1-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.54.0 (from azureml-sdk)
  Using cached azureml_train_core-1.54.0-py3-none-any.whl.metadata (1.7 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.53.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.53.0 (from azureml-sdk)
  Using cached azureml_core-1.53.0-py3-none-any.whl.metadata (3.2 kB)
Collecting azureml-dataset-runtime~=1.53.0 (from azureml-dataset-runtime[fuse]~=1.53.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.53.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.53.0 (from azureml-sdk)
  Using cached azureml_train_core-1.53.0-py3-none-any.whl.metadata (1.7 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.52.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.52.0 (from azureml-sdk)
  Using cached azureml_core-1.52.0-py3-none-any.whl.metadata (3.2 kB)
Collecting azureml-dataset-runtime~=1.52.0 (from azureml-dataset-runtime[fuse]~=1.52.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.52.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.52.0 (from azureml-sdk)
  Using cached azureml_train_core-1.52.0-py3-none-any.whl.metadata (1.7 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.51.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.51.0 (from azureml-sdk)
  Using cached azureml_core-1.51.0.post1-py3-none-any.whl.metadata (3.2 kB)
Collecting azureml-dataset-runtime~=1.51.0 (from azureml-dataset-runtime[fuse]~=1.51.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.51.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.51.0 (from azureml-sdk)
  Using cached azureml_train_core-1.51.0-py3-none-any.whl.metadata (1.7 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.50.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.50.0 (from azureml-sdk)
  Using cached azureml_core-1.50.0-py3-none-any.whl.metadata (3.2 kB)
Collecting azureml-dataset-runtime~=1.50.0 (from azureml-dataset-runtime[fuse]~=1.50.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.50.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.50.0 (from azureml-sdk)
  Using cached azureml_train_core-1.50.0-py3-none-any.whl.metadata (1.7 kB)
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
Collecting azureml-sdk
  Using cached azureml_sdk-1.49.0-py3-none-any.whl.metadata (3.6 kB)
Collecting azureml-core~=1.49.0 (from azureml-sdk)
  Using cached azureml_core-1.49.0-py3-none-any.whl.metadata (3.2 kB)
Collecting azureml-dataset-runtime~=1.49.0 (from azureml-dataset-runtime[fuse]~=1.49.0->azureml-sdk)
  Using cached azureml_dataset_runtime-1.49.0-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-train-core~=1.49.0 (from azureml-sdk)
  Using cached azureml_train_core-1.49.0.post1-py3-none-any.whl.metadata (1.7 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.25.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.24.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.23.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.22.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.21.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.20.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.19.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.18.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.17.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.16.0-py3-none-any.whl.metadata (3.7 kB)
  Using cached azureml_sdk-1.15.0-py3-none-any.whl.metadata (3.6 kB)
  Using cached azureml_sdk-1.14.0-py3-none-any.whl.metadata (3.6 kB)
  Using cached azureml_sdk-1.13.0-py3-none-any.whl.metadata (3.6 kB)
  Using cached azureml_sdk-1.12.0-py3-none-any.whl.metadata (3.6 kB)
  Using cached azureml_sdk-1.11.0-py3-none-any.whl.metadata (3.6 kB)
  Using cached azureml_sdk-1.10.0-py3-none-any.whl.metadata (3.6 kB)
  Using cached azureml_sdk-1.9.0-py3-none-any.whl.metadata (3.6 kB)
  Using cached azureml_sdk-1.8.0-py3-none-any.whl.metadata (3.6 kB)
  Using cached azureml_sdk-1.7.0.post1-py3-none-any.whl.metadata (3.6 kB)
  Using cached azureml_sdk-1.7.0-py3-none-any.whl.metadata (4.2 kB)
  Using cached azureml_sdk-1.6.0-py3-none-any.whl.metadata (4.2 kB)
  Using cached azureml_sdk-1.5.0-py3-none-any.whl.metadata (4.2 kB)
  Using cached azureml_sdk-1.4.0-py3-none-any.whl.metadata (4.2 kB)
  Using cached azureml_sdk-1.3.0-py3-none-any.whl.metadata (4.2 kB)
  Using cached azureml_sdk-1.2.0-py3-none-any.whl.metadata (4.2 kB)
  Using cached azureml_sdk-1.1.5.1-py3-none-any.whl.metadata (4.2 kB)
Collecting azureml-core==1.1.5.* (from azureml-sdk)
  Using cached azureml_core-1.1.5.7-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting azureml-train==1.1.5.* (from azureml-sdk)
  Using cached azureml_train-1.1.5-py3-none-any.whl.metadata (1.1 kB)
Collecting azureml-train-automl-client==1.1.5.* (from azureml-sdk)
  Using cached azureml_train_automl_client-1.1.5.2-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-pipeline==1.1.5.* (from azureml-sdk)
  Using cached azureml_pipeline-1.1.5-py3-none-any.whl.metadata (1.5 kB)
Collecting azureml-dataprep<1.4.0a,>=1.3.5 (from azureml-dataprep[fuse]<1.4.0a,>=1.3.5->azureml-sdk)
  Using cached azureml_dataprep-1.3.6-py3-none-any.whl.metadata (4.5 kB)
  Using cached azureml_dataprep-1.3.5-py3-none-any.whl.metadata (4.5 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.1.5-py3-none-any.whl.metadata (4.2 kB)
Collecting azureml-dataprep==1.3.2 (from azureml-dataprep[fuse]==1.3.2->azureml-sdk)
  Using cached azureml_dataprep-1.3.2-py3-none-any.whl.metadata (4.5 kB)
Collecting azureml-sdk
  Using cached azureml_sdk-1.0.85-py3-none-any.whl.metadata (4.4 kB)
Collecting azureml-core==1.0.85.* (from azureml-sdk)
  Using cached azureml_core-1.0.85.6-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting azureml-train==1.0.85.* (from azureml-sdk)
  Using cached azureml_train-1.0.85-py3-none-any.whl.metadata (1.1 kB)
Collecting azureml-train-automl-client==1.0.85.* (from azureml-sdk)
  Using cached azureml_train_automl_client-1.0.85.4-py3-none-any.whl.metadata (1.2 kB)
Collecting azureml-pipeline==1.0.85.* (from azureml-sdk)
  Using cached azureml_pipeline-1.0.85-py3-none-any.whl.metadata (1.5 kB)
Collecting azureml-dataprep<1.2.0a,>=1.1.37a (from azureml-dataprep[fuse]<1.2.0a,>=1.1.37a->azureml-sdk)
  Using cached azureml_dataprep-1.1.38-py3-none-any.whl.metadata (4.8 kB)
Requirement already satisfied: pytz in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (2025.2)
Requirement already satisfied: backports.tempfile in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (1.0)
Requirement already satisfied: pathspec in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (0.12.1)
Requirement already satisfied: requests>=2.19.1 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (2.34.2)
Collecting azure-mgmt-resource<9.0.0,>=1.2.1 (from azureml-core==1.0.85.*->azureml-sdk)
  Using cached azure_mgmt_resource-8.0.1-py2.py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: azure-mgmt-containerregistry>=2.0.0 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (14.0.0)
Requirement already satisfied: azure-mgmt-storage>=1.5.0 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (24.0.0)
Requirement already satisfied: azure-mgmt-keyvault>=0.40.0 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (11.0.0)
Requirement already satisfied: azure-mgmt-authorization>=0.40.0 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (4.0.0)
Requirement already satisfied: azure-graphrbac>=0.40.0 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (0.61.2)
Requirement already satisfied: azure-common>=1.1.12 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (1.1.28)
Requirement already satisfied: msrest>=0.5.1 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (0.7.1)
Requirement already satisfied: msrestazure>=0.4.33 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (0.6.4.post1)
Requirement already satisfied: urllib3>=1.23 in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (2.7.0)
Requirement already satisfied: six>=1.11.0 in C:\Users\gael1\AppData\Roaming\Python\Python314\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (1.17.0)
Requirement already satisfied: cryptography!=1.9,!=2.0.*,!=2.1.*,!=2.2.* in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (46.0.7)
Requirement already satisfied: python-dateutil>=2.7.3 in C:\Users\gael1\AppData\Roaming\Python\Python314\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (2.9.0.post0)
Requirement already satisfied: ndg-httpsclient in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (0.5.1)
Requirement already satisfied: SecretStorage in C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages (from azureml-core==1.0.85.*->azureml-sdk) (3.5.0)
Collecting ruamel.yaml<=0.15.89,>=0.15.35 (from azureml-core==1.0.85.*->azureml-sdk)
  Using cached ruamel.yaml-0.15.89.tar.gz (306 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

WARNING: Ignoring version 1.3.6 of azureml-dataprep since it has invalid metadata:
Requested azureml-dataprep<1.4.0a,>=1.3.5 from https://files.pythonhosted.org/packages/9f/b3/a5604bc6bbdc85982d63580ecf2febf3f66f9aecb45969ad7dcf9db89987/azureml_dataprep-1.3.6-py3-none-any.whl (from azureml-dataprep[fuse]<1.4.0a,>=1.3.5->azureml-sdk) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    pyarrow (>=0.15.*) ; extra == 'pandas'
             ~~~~~~~^
Please use pip<24.1 if you need to use this version.
WARNING: Ignoring version 1.3.5 of azureml-dataprep since it has invalid metadata:
Requested azureml-dataprep<1.4.0a,>=1.3.5 from https://files.pythonhosted.org/packages/9b/c8/7155020ae91f33d9baeebae72f78679390d704a25fb5cfb878fc48eb596c/azureml_dataprep-1.3.5-py3-none-any.whl (from azureml-dataprep[fuse]<1.4.0a,>=1.3.5->azureml-sdk) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    pyarrow (>=0.15.*) ; extra == 'pandas'
             ~~~~~~~^
Please use pip<24.1 if you need to use this version.
WARNING: Ignoring version 1.3.2 of azureml-dataprep since it has invalid metadata:
Requested azureml-dataprep==1.3.2 from https://files.pythonhosted.org/packages/00/61/8246d58b7f1187cccff41fbe1aa8b1e10337b00c3c9118b9d5f0be38b52c/azureml_dataprep-1.3.2-py3-none-any.whl (from azureml-dataprep[fuse]==1.3.2->azureml-sdk) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    pyarrow (>=0.15.*) ; extra == 'pandas'
             ~~~~~~~^
Please use pip<24.1 if you need to use this version.
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 389, in <module>
          main()
          ~~~~^^
        File "C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 373, in main
          json_out["return_val"] = hook(**hook_input["kwargs"])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 143, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\gael1\AppData\Local\Temp\pip-build-env-ayq_w1kk\overlay\Lib\site-packages\setuptools\build_meta.py", line 333, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gael1\AppData\Local\Temp\pip-build-env-ayq_w1kk\overlay\Lib\site-packages\setuptools\build_meta.py", line 301, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\gael1\AppData\Local\Temp\pip-build-env-ayq_w1kk\overlay\Lib\site-packages\setuptools\build_meta.py", line 520, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\gael1\AppData\Local\Temp\pip-build-env-ayq_w1kk\overlay\Lib\site-packages\setuptools\build_meta.py", line 317, in run_setup
          exec(code, locals())  # noqa: S102 # exec is intentional here
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 50, in <module>
      ImportError: cannot import name 'Str' from 'ast' (C:\Users\gael1\AppData\Local\Programs\Python\Python314\Lib\ast.py)
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed to build 'ruamel.yaml' when getting requirements to build wheel

In [4]:

import kagglehub
import pandas as pd
path = kagglehub.dataset_download("fedesoriano/company-bankruptcy-prediction")
data = pd.read_csv(path+"/data.csv")

In [5]:
data

,Bankrupt?,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,1,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1,0.016469
1,1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1,0.020794
2,1,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1,0.016474
3,1,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1,0.023982
4,1,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1,0.035490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6814,0,0.493687,0.539468,0.543230,0.604455,0.604462,0.998992,0.797409,0.809331,0.303510,...,0.799927,0.000466,0.623620,0.604455,0.840359,0.279606,0.027064,0.566193,1,0.029890
6815,0,0.475162,0.538269,0.524172,0.598308,0.598308,0.998992,0.797414,0.809327,0.303520,...,0.799748,0.001959,0.623931,0.598306,0.840306,0.278132,0.027009,0.566018,1,0.038284
6816,0,0.472725,0.533744,0.520638,0.610444,0.610213,0.998984,0.797401,0.809317,0.303512,...,0.797778,0.002840,0.624156,0.610441,0.840138,0.275789,0.026791,0.565158,1,0.097649
6817,0,0.506264,0.559911,0.554045,0.607850,0.607850,0.999074,0.797500,0.809399,0.303498,...,0.811808,0.002837,0.623957,0.607846,0.841084,0.277547,0.026822,0.565302,1,0.044009
6818,0,0.493053,0.570105,0.549548,0.627409,0.627409,0.998080,0.801987,0.813800,0.313415,...,0.815956,0.000707,0.626680,0.627408,0.841019,0.275114,0.026793,0.565167,1,0.233902

In [6]:
import azureml

In [7]:
df=data.copy()

In [8]:
features= df.drop(['Bankrupt?'], axis=1)
features

,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,Continuous interest rate (after tax),...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,0.370594,0.424389,0.405750,0.601457,0.601457,0.998969,0.796887,0.808809,0.302646,0.780985,...,0.716845,0.009219,0.622879,0.601453,0.827890,0.290202,0.026601,0.564050,1,0.016469
1,0.464291,0.538214,0.516730,0.610235,0.610235,0.998946,0.797380,0.809301,0.303556,0.781506,...,0.795297,0.008323,0.623652,0.610237,0.839969,0.283846,0.264577,0.570175,1,0.020794
2,0.426071,0.499019,0.472295,0.601450,0.601364,0.998857,0.796403,0.808388,0.302035,0.780284,...,0.774670,0.040003,0.623841,0.601449,0.836774,0.290189,0.026555,0.563706,1,0.016474
3,0.399844,0.451265,0.457733,0.583541,0.583541,0.998700,0.796967,0.808966,0.303350,0.781241,...,0.739555,0.003252,0.622929,0.583538,0.834697,0.281721,0.026697,0.564663,1,0.023982
4,0.465022,0.538432,0.522298,0.598783,0.598783,0.998973,0.797366,0.809304,0.303475,0.781550,...,0.795016,0.003878,0.623521,0.598782,0.839973,0.278514,0.024752,0.575617,1,0.035490
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6814,0.493687,0.539468,0.543230,0.604455,0.604462,0.998992,0.797409,0.809331,0.303510,0.781588,...,0.799927,0.000466,0.623620,0.604455,0.840359,0.279606,0.027064,0.566193,1,0.029890
6815,0.475162,0.538269,0.524172,0.598308,0.598308,0.998992,0.797414,0.809327,0.303520,0.781586,...,0.799748,0.001959,0.623931,0.598306,0.840306,0.278132,0.027009,0.566018,1,0.038284
6816,0.472725,0.533744,0.520638,0.610444,0.610213,0.998984,0.797401,0.809317,0.303512,0.781546,...,0.797778,0.002840,0.624156,0.610441,0.840138,0.275789,0.026791,0.565158,1,0.097649
6817,0.506264,0.559911,0.554045,0.607850,0.607850,0.999074,0.797500,0.809399,0.303498,0.781663,...,0.811808,0.002837,0.623957,0.607846,0.841084,0.277547,0.026822,0.565302,1,0.044009
6818,0.493053,0.570105,0.549548,0.627409,0.627409,0.998080,0.801987,0.813800,0.313415,0.786079,...,0.815956,0.000707,0.626680,0.627408,0.841019,0.275114,0.026793,0.565167,1,0.233902

In [9]:
labels= df['Bankrupt?']

In [10]:
import pandas as pd
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    features, labels, test_size=0.2, random_state=42)

In [11]:
from sklearn.linear_model import LogisticRegression
reg = LogisticRegression().fit(X_train, y_train)

pred = reg.predict(X_test)

from sklearn.metrics import accuracy_score, r2_score

r2 = accuracy_score(pred, y_test)
r2

c:\Users\gael1\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.9611436950146628

In [12]:
import pickle

file = open('logistic_regressor.pkl', 'wb')
pickle.dump(reg, file)
file.close()

# DESPLEGANDO EN LA NUBE.

Lo primero que debemos hacer es generar un espacio de trabajo (workspace), utilizando para ello el id de nuestra suscripción.

In [13]:
#GETTING MY ID:
import json

id = open('my_id.json', 'r')
mi = json.load(id)

from azureml.core import Workspace

ws = Workspace.get(name="hw1_car_pricing",
                      subscription_id = mi["my_id"],
                      resource_group = "__hw1__",
                      location = "swedencentral") #centralindia

In [14]:
from azureml.core.model import Model

registered_model = Model.register(model_path="logistic_regressor.pkl",
                                  model_name="bankruptcy_model",
                                  workspace=ws)

Registering model bankruptcy_model

In [15]:
from azureml.core.environment import Environment
virtual_env = Environment("env-4-housing")

from azureml.core.conda_dependencies import CondaDependencies
virtual_env.python.conda_dependencies = CondaDependencies.create(conda_packages=[
    'pandas',
    'scikit-learn'
    ])

In [28]:
################ score.py ###################

scorepy = """
import json
import joblib
import numpy as np
import pandas as pd
from azureml.core.model import Model

def init():
  global model
  model_path = Model.get_model_path('bankruptcy_model')
  model = joblib.load(model_path)

def run(raw_data):
  try:
    data = json.loads(raw_data)
    data = pd.DataFrame(data)

    result = model.predict(data)

    return json.dumps({"result": result.tolist()})

  except Exception as e:
    return json.dumps({"error": str(e)})
"""

file_score = open("score.py", "w")
file_score.write(scorepy)
file_score.close()

In [ ]:
from azureml.core.model import InferenceConfig
from azureml.core.webservice import AciWebservice

inference_config = InferenceConfig(
                                environment=virtual_env,
                                entry_script="score.py",
                                )
aci_config = AciWebservice.deploy_configuration(cpu_cores=0.5, memory_gb=1)

service = Model.deploy(workspace=ws,
                        name='bankruptcy-service',
                       models=[registered_model],
                       inference_config=inference_config,
                       deployment_config=aci_config,
                       overwrite=True,
                       )

C:\Users\gael1\AppData\Local\Temp\ipykernel_91104\3507369934.py:10: FutureWarning: azureml.core.model:
To leverage new model deployment capabilities, AzureML recommends using CLI/SDK v2 to deploy models as online endpoint,
please refer to respective documentations
https://docs.microsoft.com/azure/machine-learning/how-to-deploy-managed-online-endpoints /
https://docs.microsoft.com/azure/machine-learning/how-to-attach-kubernetes-anywhere
For more information on migration, see https://aka.ms/acimoemigration
To disable CLI/SDK v1 deprecation warning set AZUREML_LOG_DEPRECATION_WARNING_ENABLED to 'False'
  service = Model.deploy(workspace=ws,

In [30]:
service.wait_for_deployment()

ACI service creation operation finished, operation "Succeeded"

In [31]:
scoring_uri = service.scoring_uri

In [32]:
print(service.get_logs())

/bin/bash: /azureml-envs/azureml_0e3eef4adb0a80c1bf43b424432d4d5d/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/bin/bash: /azureml-envs/azureml_0e3eef4adb0a80c1bf43b424432d4d5d/lib/libtinfo.so.6: no version information available (required by /bin/bash)
/bin/bash: /azureml-envs/azureml_0e3eef4adb0a80c1bf43b424432d4d5d/lib/libtinfo.so.6: no version information available (required by /bin/bash)
2026-09-30T21:55:50,475648307+00:00 - rsyslog/run
bash: /azureml-envs/azureml_0e3eef4adb0a80c1bf43b424432d4d5d/lib/libtinfo.so.6: no version information available (required by bash)
2026-09-30T21:55:50,483801084+00:00 - gunicorn/run
2026-09-30T21:55:50,488734382+00:00 - nginx/run
2026-09-30T21:55:50,491978461+00:00 | gunicorn/run |
2026-09-30T21:55:50,496453253+00:00 | gunicorn/run | ###############################################
2026-09-30T21:55:50,498303251+00:00 | gunicorn/run | AzureML Container Runtime Information
2026-09-30T21:55:50,501488254+00:00 | gunicorn/run | ###############################################
2026-09-30T21:55:50,505133788+00:00 | gunicorn/run |
2026-09-30T21:55:50,506722167+00:00 | gunicorn/run |
2026-09-30T21:55:50,517062397+00:00 | gunicorn/run | AzureML image information: openmpi4.1.0-ubuntu22.04, Materializaton Build:20251130.v1
2026-09-30T21:55:50,521585130+00:00 | gunicorn/run |
2026-09-30T21:55:50,523729445+00:00 | gunicorn/run |
2026-09-30T21:55:50,526371861+00:00 | gunicorn/run | PATH environment variable: /azureml-envs/azureml_0e3eef4adb0a80c1bf43b424432d4d5d/bin:/opt/miniconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
2026-09-30T21:55:50,528549199+00:00 | gunicorn/run | PYTHONPATH environment variable:
2026-09-30T21:55:50,530714764+00:00 | gunicorn/run |
/opt/miniconda/lib/python3.10/site-packages/conda/cli/conda_argparse.py:253: FutureWarning: `--root` is deprecated and will be removed in 26.3. Use `--base` instead.
  super().__call__(parser, namespace, values, option_string)
2026-09-30T21:55:51,265519618+00:00 | gunicorn/run | CONDAPATH environment variable: /opt/miniconda


# conda environments:
#
# * -> active
# + -> frozen
                     *   /azureml-envs/azureml_0e3eef4adb0a80c1bf43b424432d4d5d
base                     /opt/miniconda

2026-09-30T21:55:51,699538866+00:00 | gunicorn/run |
2026-09-30T21:55:51,700940546+00:00 | gunicorn/run | Pip Dependencies (before dynamic installation)

adal==1.2.7
annotated-types==0.8.0
argcomplete==3.7.2
attrs==26.1.0
azure-common==1.1.28
azure-core==1.41.0
azure-graphrbac==0.61.2
azure-identity==1.17.0
azure-mgmt-authorization==4.0.0
azure-mgmt-containerregistry==14.0.0
azure-mgmt-core==1.6.0
azure-mgmt-keyvault==11.0.0
azure-mgmt-network==30.0.0
azure-mgmt-resource==24.0.0
azure-mgmt-storage==24.0.0
azure-monitor-opentelemetry-exporter==1.0.0b40
azureml-core==1.61.0.post4
azureml-dataprep==5.5.0
azureml-dataprep-native==43.0.0
azureml-dataprep-rslex==2.26.1
azureml-dataset-runtime==1.62.0.post1
azureml-defaults==1.62.0
azureml-inference-server-http==1.5.1
backports.tempfile==1.0
backports.weakref==1.0.post1
bcrypt==5.0.0
blinker==1.9.0
Bottleneck @ file:///home/task_X4xAKm7cQsS3M_0/croot/bottleneck_1783928145346/work
certifi==2026.7.22
cffi==2.1.1
charset-normalizer==3.5.1
click==8.5.0
cloudpickle==2.2.1
contextlib2==21.6.0
cryptography==46.0.7
Deprecated==1.3.1
docker==7.2.0
fixedint==0.1.6
Flask==3.1.3
flask-cors==6.0.5
fusepy==3.0.1
gunicorn==26.2.0
humanfriendly==10.0
idna==3.20
importlib_metadata==8.6.1
inference-schema==1.8
isodate==0.7.2
itsdangerous==2.2.0
jeepney==0.9.0
Jinja2==3.1.6
jmespath==1.1.0
joblib @ file:///home/task_176786809611178/croot/joblib_1767868117348/work
jsonpickle==4.1.2
jsonschema==4.26.0
jsonschema-specifications==2025.9.1
knack==0.12.0
MarkupSafe==3.0.3
msal==1.39.0
msal-extensions==1.3.1
msrest==0.7.1
msrestazure==0.6.4.post1
ndg-httpsclient==0.5.1
numexpr @ file:///home/task_177626999680288/croot/numexpr_1776270041084/work
numpy @ file:///home/task_177619048017470/croot/numpy_and_numpy_base_1776190523231/work/dist/numpy-2.2.5-cp310-cp310-linux_x86_64.whl#sha256=c99163920ec04185b821c50ea17d5980a99e332b201655ebba944601fa4850d9
oauthlib==3.3.1
opentelemetry-api==1.33.0
opentelemetry-sdk==1.33.0
opentelemetry-semantic-conventions==0.54b0
packaging==25.0
pandas @ file:///home/task_176233228161209/conda-bld/pandas_1762332325727/work/dist/pandas-2.3.3-cp310-cp310-linux_x86_64.whl#sha256=cd4241f338dbf9922b2bc5a62ff6267574e607e9e9ea8b5efbba07b037c96f8f
paramiko==3.5.1
pathspec==0.12.1
pkginfo==1.13
psutil==7.2.2
pyarrow==23.0.1
pyasn1==0.6.4
pycparser==3.0
pydantic==2.12.5
pydantic-settings==2.15.0
pydantic_core==2.41.5
Pygments==2.21.0
PyJWT==2.15.0
PyNaCl==1.6.2
pyOpenSSL==26.0.0
PySocks==1.7.1
python-dateutil @ file:///croot/python-dateutil_1716495738603/work
python-dotenv==1.2.3
pytz @ file:///home/task_178668616065337/croot/pytz_1786686189911/work
PyYAML==6.0.3
referencing==0.37.0
requests==2.34.2
requests-oauthlib==2.0.0
rpds-py==0.30.0
scikit-learn @ file:///home/task_176483814803112/conda-bld/scikit-learn_1764838161684/work
scipy @ file:///home/task_177627750370193/croot/scipy_1776277546347/work/dist/scipy-1.15.3-cp310-cp310-linux_x86_64.whl#sha256=6371f86bd6f3a564c77dd43b6a260d5167d50fa94f4ab6a05f078e773ec47fd7
SecretStorage==3.5.0
six @ file:///croot/six_1744271502820/work
tabulate==0.10.0
threadpoolctl @ file:///home/task_176436167996728/conda-bld/threadpoolctl_1764361727999/work
typing-inspection==0.4.4
typing_extensions==4.16.0
tzdata @ file:///home/task_178834294813729/croot/python-tzdata_1788343367872/work
urllib3==2.8.0
Werkzeug==3.1.8
wrapt==1.16.0
zipp==4.1.0

2026-09-30T21:55:52,272286685+00:00 | gunicorn/run |
2026-09-30T21:55:52,273463124+00:00 | gunicorn/run | Entry script directory: /var/azureml-app/.
2026-09-30T21:55:52,274944141+00:00 | gunicorn/run |
2026-09-30T21:55:52,276103528+00:00 | gunicorn/run | ###############################################
2026-09-30T21:55:52,277331743+00:00 | gunicorn/run | Dynamic Python Package Installation
2026-09-30T21:55:52,278502050+00:00 | gunicorn/run | ###############################################
2026-09-30T21:55:52,280290954+00:00 | gunicorn/run |
2026-09-30T21:55:52,281760029+00:00 | gunicorn/run | Dynamic Python package installation is disabled.
2026-09-30T21:55:52,283501424+00:00 | gunicorn/run |
2026-09-30T21:55:52,284860935+00:00 | gunicorn/run | ###############################################
2026-09-30T21:55:52,286265490+00:00 | gunicorn/run | Checking if the Python package azureml-inference-server-http is installed
2026-09-30T21:55:52,287468868+00:00 | gunicorn/run | ###############################################
2026-09-30T21:55:52,288644356+00:00 | gunicorn/run |
2026-09-30T21:55:52,702598988+00:00 | gunicorn/run |
2026-09-30T21:55:52,704003072+00:00 | gunicorn/run | ###############################################
2026-09-30T21:55:52,705746911+00:00 | gunicorn/run | AzureML Inference Server
2026-09-30T21:55:52,706991577+00:00 | gunicorn/run | ###############################################
2026-09-30T21:55:52,708679111+00:00 | gunicorn/run |
2026-09-30T21:55:52,710180216+00:00 | gunicorn/run | Starting AzureML Inference Server HTTP.
2026-09-30 21:55:52,919 I [67] azmlinfsrv - Loaded logging config from /azureml-envs/azureml_0e3eef4adb0a80c1bf43b424432d4d5d/lib/python3.10/site-packages/azureml_inference_server_http/logging.json
2026-09-30 21:55:52,955 I [67] gunicorn.error - Starting gunicorn 26.2.0
2026-09-30 21:55:52,956 I [67] gunicorn.error - Listening at: http://0.0.0.0:31311 (67)
2026-09-30 21:55:52,956 I [67] gunicorn.error - Using worker: sync
2026-09-30 21:55:52,958 I [119] gunicorn.error - Booting worker with pid: 119
2026-09-30 21:55:53,049 I [67] gunicorn.error - Control socket listening at /root/.gunicorn/gunicorn.ctl

Azure ML Inferencing HTTP server v1.5.1


Server Settings
---------------
Entry Script Name: /var/azureml-app/score.py
Model Directory: /var/azureml-app/azureml-models/bankruptcy_model/1
Config File: None
Worker Count: 1
Worker Timeout (seconds): 300
Server Port: 31311
Health Port: 31311
Application Insights Enabled: false
Application Insights Key: None
Inferencing HTTP server version: azmlinfsrv/1.5.1
CORS for the specified origins: None
Create dedicated endpoint for health: None


Server Routes
---------------
Liveness Probe: GET   127.0.0.1:31311/
Score:          POST  127.0.0.1:31311/score

2026-09-30 21:55:53,166 W [119] azmlinfsrv - Found extra keys in the config file that are not supported by the server.
Extra keys = ['AZUREML_ENTRY_SCRIPT', 'SERVICE_NAME', 'WORKSPACE_NAME', 'SCORING_TIMEOUT_MS', 'AZUREML_MODEL_DIR', 'HOSTNAME']
Initializing logger
2026-09-30 21:55:53,675 I [119] azmlinfsrv - Starting up app insights client
2026-09-30 21:55:55,434 I [119] azmlinfsrv.user_script - Found user script at /var/azureml-app/score.py
2026-09-30 21:55:55,435 I [119] azmlinfsrv.user_script - run() is not decorated. Server will invoke it with the input in JSON string.
2026-09-30 21:55:55,435 I [119] azmlinfsrv.user_script - Invoking user's init function
2026-09-30 21:55:56,339 I [119] azmlinfsrv.user_script - Users's init has completed successfully
/azureml-envs/azureml_0e3eef4adb0a80c1bf43b424432d4d5d/lib/python3.10/site-packages/sklearn/base.py:442: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.6.1 when using version 1.7.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
2026-09-30 21:55:56,341 I [119] azmlinfsrv.swagger - Swaggers are prepared for the following versions: [2, 3, 3.1].
2026-09-30 21:55:56,341 I [119] azmlinfsrv - Scoring timeout is set to 60000
2026-09-30 21:55:56,341 I [119] azmlinfsrv - Worker with pid 119 ready for serving traffic
2026-09-30 21:57:06,274 W [119] azmlinfsrv - x-ms-request-id header has been deprecated and will be removed from future versions of the server. Please use x-ms-client-request-id.
2026-09-30 21:57:06,276 I [119] gunicorn.access - 127.0.0.1 - - [30/Sep/2026:21:57:06 +0000] "GET / HTTP/1.0" 200 7 "-" "Go-http-client/1.1"
2026-09-30 21:57:06,281 W [119] azmlinfsrv - x-ms-request-id header has been deprecated and will be removed from future versions of the server. Please use x-ms-client-request-id.
2026-09-30 21:57:06,282 I [119] azmlinfsrv - GET /swagger.json 200 1.646ms 2214
2026-09-30 21:57:06,283 I [119] gunicorn.access - 127.0.0.1 - - [30/Sep/2026:21:57:06 +0000] "GET /swagger.json HTTP/1.0" 200 2214 "-" "Go-http-client/1.1"
2026-09-30 21:57:57,223 W [119] azmlinfsrv - x-ms-request-id header has been deprecated and will be removed from future versions of the server. Please use x-ms-client-request-id.
2026-09-30 21:57:57,225 I [119] gunicorn.access - 127.0.0.1 - - [30/Sep/2026:21:57:57 +0000] "GET / HTTP/1.0" 200 7 "-" "Go-http-client/1.1"
2026-09-30 21:57:57,234 W [119] azmlinfsrv - x-ms-request-id header has been deprecated and will be removed from future versions of the server. Please use x-ms-client-request-id.
2026-09-30 21:57:57,235 I [119] azmlinfsrv - GET /swagger.json 200 0.546ms 2214
2026-09-30 21:57:57,236 I [119] gunicorn.access - 127.0.0.1 - - [30/Sep/2026:21:57:57 +0000] "GET /swagger.json HTTP/1.0" 200 2214 "-" "Go-http-client/1.1"

In [33]:
prueba=pd.read_csv("prueba.csv")
prueba.drop(['Unnamed: 0',"Bankrupt?"], axis=1, inplace=True)
prueba

,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,Continuous interest rate (after tax),...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,302583.846829,215926.668338,160681.375234,113789.973083,363023.506580,21337.201274,391837.887305,401233.992710,-3081.409915,339932.913561,...,-20803.840865,-31727.661064,254483.525085,91398.771828,185869.684595,56136.475541,6439.213877,194339.999725,218748,-21751.619260
1,296828.273778,213045.320105,155028.177793,111604.727814,357377.710979,21333.981513,391764.751701,401162.054605,-3081.382844,339868.922278,...,-20816.707256,-32506.279096,251459.324081,89736.384811,186528.801063,63877.101621,6446.586494,194383.053127,218748,-30299.884588
2,327271.457125,234716.999128,172092.136838,114193.628800,364066.390738,21337.086282,392031.534720,401360.048787,-3074.991683,340061.212601,...,-20231.915888,-30668.672365,251464.519612,91705.142213,186246.487611,55978.622787,6426.802673,194262.498897,218748,-18209.737872
3,269715.726612,192432.598125,142886.849135,109683.693560,352414.530463,21329.381856,391660.207706,401078.740547,-3081.355773,339795.500035,...,-21387.657854,-27070.202705,251224.732013,88276.137513,185237.572268,58382.352910,6204.241904,187676.849320,218748,-29077.210429
4,322100.206211,225137.131923,173448.904224,113136.784740,361335.930397,21336.807017,391821.994810,401217.421958,-3081.631403,339927.723368,...,-20465.789236,-32166.781557,250142.316882,90901.039680,186230.436500,56715.036089,6434.530874,194311.528008,218748,-26386.100504
5,287800.496758,205263.217183,150540.408748,111140.523739,356173.653815,21333.114149,391748.557926,401150.086840,-3081.267178,339858.162122,...,-20915.443338,-28434.561754,251408.065819,89383.825463,185875.550424,57709.995625,6441.210105,194351.866011,218748,-28496.495732
6,289348.950422,207184.116005,153619.227046,112415.708846,359472.960060,21334.106361,391770.174732,401170.076953,-3081.301632,339880.188795,...,-20859.146789,-22364.276630,251398.005486,90352.769763,185871.470625,56714.641320,6442.092860,194357.063173,218748,-26384.535195
7,252361.359138,181128.847362,133615.605332,111678.119762,357567.326280,21332.325637,391628.949955,401066.707025,-3084.582116,339766.067843,...,-21519.365535,-32513.768574,251241.135760,89792.593103,185154.893963,57580.732969,6396.280314,194039.800334,218748,-28340.347833
8,344070.718569,233264.011557,181311.197280,116030.262313,368124.158189,21339.918357,391902.963683,401261.742144,-3081.318859,339967.599241,...,-20298.628357,-26092.502522,238024.075425,93102.294268,186386.240393,56728.261505,6427.416966,194266.493014,218748,-26437.924626
9,282191.004241,203982.617968,150679.564377,114184.454806,364042.688825,21331.116584,391896.109574,401297.711196,-3074.944925,340042.477270,...,-20934.411461,-29021.142846,251018.642896,91698.156767,185792.157626,56500.961406,6460.832308,194460.613492,218748,-25342.485140

In [34]:
headers = {"Content-Type": "application/json"}

import requests
response = requests.post(scoring_uri, 
                         data=prueba.to_json(orient='records'), 
                         headers=headers)

if response.status_code == 200:
  result = json.loads(response.json())
  print("S")
  print(result)
  prueba["Bankrupt?"] = result["result"]
  display(pd.DataFrame(prueba))
else:
  print(f"Error: {response.text}")

S
{'result': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}

,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,Continuous interest rate (after tax),...,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability,Bankrupt?
0,302583.846829,215926.668338,160681.375234,113789.973083,363023.506580,21337.201274,391837.887305,401233.992710,-3081.409915,339932.913561,...,-31727.661064,254483.525085,91398.771828,185869.684595,56136.475541,6439.213877,194339.999725,218748,-21751.619260,0
1,296828.273778,213045.320105,155028.177793,111604.727814,357377.710979,21333.981513,391764.751701,401162.054605,-3081.382844,339868.922278,...,-32506.279096,251459.324081,89736.384811,186528.801063,63877.101621,6446.586494,194383.053127,218748,-30299.884588,0
2,327271.457125,234716.999128,172092.136838,114193.628800,364066.390738,21337.086282,392031.534720,401360.048787,-3074.991683,340061.212601,...,-30668.672365,251464.519612,91705.142213,186246.487611,55978.622787,6426.802673,194262.498897,218748,-18209.737872,0
3,269715.726612,192432.598125,142886.849135,109683.693560,352414.530463,21329.381856,391660.207706,401078.740547,-3081.355773,339795.500035,...,-27070.202705,251224.732013,88276.137513,185237.572268,58382.352910,6204.241904,187676.849320,218748,-29077.210429,0
4,322100.206211,225137.131923,173448.904224,113136.784740,361335.930397,21336.807017,391821.994810,401217.421958,-3081.631403,339927.723368,...,-32166.781557,250142.316882,90901.039680,186230.436500,56715.036089,6434.530874,194311.528008,218748,-26386.100504,0
5,287800.496758,205263.217183,150540.408748,111140.523739,356173.653815,21333.114149,391748.557926,401150.086840,-3081.267178,339858.162122,...,-28434.561754,251408.065819,89383.825463,185875.550424,57709.995625,6441.210105,194351.866011,218748,-28496.495732,0
6,289348.950422,207184.116005,153619.227046,112415.708846,359472.960060,21334.106361,391770.174732,401170.076953,-3081.301632,339880.188795,...,-22364.276630,251398.005486,90352.769763,185871.470625,56714.641320,6442.092860,194357.063173,218748,-26384.535195,0
7,252361.359138,181128.847362,133615.605332,111678.119762,357567.326280,21332.325637,391628.949955,401066.707025,-3084.582116,339766.067843,...,-32513.768574,251241.135760,89792.593103,185154.893963,57580.732969,6396.280314,194039.800334,218748,-28340.347833,0
8,344070.718569,233264.011557,181311.197280,116030.262313,368124.158189,21339.918357,391902.963683,401261.742144,-3081.318859,339967.599241,...,-26092.502522,238024.075425,93102.294268,186386.240393,56728.261505,6427.416966,194266.493014,218748,-26437.924626,0
9,282191.004241,203982.617968,150679.564377,114184.454806,364042.688825,21331.116584,391896.109574,401297.711196,-3074.944925,340042.477270,...,-29021.142846,251018.642896,91698.156767,185792.157626,56500.961406,6460.832308,194460.613492,218748,-25342.485140,0